// PitchBridge Demo Data

export const demoUsers = [
  { id: 1, name: 'Aakshna Sharma', email: 'founder@demo.com', password: 'demo123', role: 'founder', avatar: 'AS', company: 'NeuralNest AI', bio: 'Building the future of human-AI collaboration.', tagline: 'AI for Everyone', location: 'Bangalore, India', connections: 142 },
  { id: 2, name: 'Rahul Mehta', email: 'investor@demo.com', password: 'demo123', role: 'investor', avatar: 'RM', company: 'Sequoia India', bio: 'Early-stage investor backing deep-tech founders.', tagline: 'Seed to Series A', location: 'Mumbai, India', connections: 389 },
  { id: 3, name: 'Priya Nair', email: 'seeker@demo.com', password: 'demo123', role: 'seeker', avatar: 'PN', bio: 'Full-stack developer passionate about startups.', tagline: 'React • Node • PostgreSQL', location: 'Hyderabad, India', connections: 67 },
];

export const demoStartups = [
  {
    id: 1,
    name: 'NeuralNest AI',
    founder: 'Aakshna Sharma',
    founderId: 1,
    tagline: 'Context-aware AI assistant for enterprise teams',
    problem: 'Enterprise teams lose 40% of productivity due to scattered knowledge and poor tool integration.',
    solution: 'An AI layer that sits on top of all existing tools, learns context, and automates routine workflows.',
    traction: '12 pilot customers, $48K ARR, 3 months old.',
    market: '$47B enterprise AI market growing at 32% CAGR.',
    sector: ['AI/ML', 'SaaS', 'Enterprise'],
    stage: 'Pre-Seed',
    askAmount: '$500K',
    aiScore: 92,
    aiSummary: 'High-conviction opportunity. Strong problem-solution fit in a massive market. Early traction signals product-market fit. Founder has relevant domain expertise. Risk: competitive landscape from incumbents.',
    logo: '🧠',
    color: '#3B82F6',
  },
  {
    id: 2,
    name: 'GreenGrid Energy',
    founder: 'Vikram Patel',
    founderId: 5,
    tagline: 'Peer-to-peer renewable energy trading platform',
    problem: 'Excess solar energy from rooftop panels goes to waste; utility grids poorly incentivize prosumers.',
    solution: 'Blockchain-based P2P exchange letting households sell surplus energy to neighbors in real-time.',
    traction: '3 pilots in Gujarat, 200 enrolled households, $12K MRR.',
    market: '$1.2T global energy market; renewables segment at $500B.',
    sector: ['CleanTech', 'Blockchain', 'Energy'],
    stage: 'Seed',
    askAmount: '$1.2M',
    aiScore: 85,
    aiSummary: 'Compelling climate-tech play with regulatory tailwinds. Blockchain adds friction — evaluate if necessary. Pilot data is strong. Founder background in energy infrastructure is a plus.',
    logo: '⚡',
    color: '#10B981',
  },
  {
    id: 3,
    name: 'MediScan Pro',
    founder: 'Deepa Krishnan',
    founderId: 6,
    tagline: 'AI-powered radiology second opinions in 60 seconds',
    problem: 'Radiologist shortage causes 3-5 day delays in scan reads, risking patient outcomes.',
    solution: 'Computer vision model trained on 2M+ scans provides instant preliminary read for ER triage.',
    traction: '7 hospital partners, FDA 510(k) submission in progress, $80K monthly recurring from pilots.',
    market: '$13B radiology AI market.',
    sector: ['HealthTech', 'AI/ML', 'MedTech'],
    stage: 'Series A',
    askAmount: '$4M',
    aiScore: 96,
    aiSummary: 'Exceptional execution. High-impact vertical with defensible moat (proprietary dataset + FDA pathway). Revenue traction at Series A stage is impressive. Primary risk is regulatory timeline.',
    logo: '🏥',
    color: '#8B5CF6',
  },
  {
    id: 4,
    name: 'AgriSense',
    founder: 'Suresh Gupta',
    founderId: 7,
    tagline: 'IoT + ML crop advisory for smallholder farmers',
    problem: 'Indian smallholder farmers lack access to precision agriculture data, causing 30% yield loss.',
    solution: 'Low-cost IoT sensors + satellite imagery + LLM chatbot delivering hyper-local crop advice via SMS.',
    traction: '2,000 farmers onboarded, ₹18L ARR, partnered with 3 state agriculture departments.',
    market: '$24B precision agriculture market in South/Southeast Asia.',
    sector: ['AgriTech', 'IoT', 'AI/ML'],
    stage: 'Seed',
    askAmount: '$800K',
    aiScore: 78,
    aiSummary: 'Strong social impact. Revenue model needs stress-testing (farmer willingness-to-pay is historically low). Government partnerships de-risk distribution. Evaluate unit economics carefully.',
    logo: '🌾',
    color: '#F59E0B',
  },
  {
    id: 5,
    name: 'SkillBridge',
    founder: 'Ananya Reddy',
    founderId: 8,
    tagline: 'Micro-credential platform for blue-collar upskilling',
    problem: 'India has 400M blue-collar workers with no structured path to skill upgrades or career growth.',
    solution: 'Mobile-first, vernacular-language micro-courses with employer-verified certifications in 2-week sprints.',
    traction: '15,000 monthly active learners, 42 employer partnerships, ₹35L MRR.',
    market: 'India vocational training market: $10B.',
    sector: ['EdTech', 'HRTech', 'Social Impact'],
    stage: 'Series A',
    askAmount: '$2.5M',
    aiScore: 88,
    aiSummary: 'Scalable model with clear unit economics and strong employer demand signal. Retention data is the key metric — request cohort analysis. Vernacular approach is a genuine differentiator.',
    logo: '📚',
    color: '#EC4899',
  },
];

export const demoJobs = [
  {
    id: 1,
    title: 'Senior Full-Stack Engineer',
    company: 'NeuralNest AI',
    founderId: 1,
    location: 'Bangalore (Remote OK)',
    type: 'Full-time',
    salary: '₹25L – ₹40L',
    equity: '0.1% – 0.5%',
    stack: ['React', 'Node.js', 'PostgreSQL', 'Python', 'Docker'],
    description: 'Own the engineering of core product features. Work directly with the founding team to build scalable, production-grade systems that handle enterprise-grade data.',
    requirements: ['5+ years full-stack experience', 'Strong TypeScript skills', 'Experience with LLM APIs', 'Startup mindset'],
    posted: '2 days ago',
    applicants: 18,
    logo: '🧠',
  },
  {
    id: 2,
    title: 'Product Designer (UI/UX)',
    company: 'GreenGrid Energy',
    founderId: 5,
    location: 'Ahmedabad / Remote',
    type: 'Full-time',
    salary: '₹12L – ₹20L',
    equity: '0.05% – 0.2%',
    stack: ['Figma', 'Framer', 'CSS', 'Design Systems'],
    description: 'Design the consumer-facing energy trading app and the prosumer dashboard. You will define how 200+ households interact with their energy in real-time.',
    requirements: ['3+ years product design', 'Experience with energy/fintech apps preferred', 'Strong portfolio required'],
    posted: '5 days ago',
    applicants: 31,
    logo: '⚡',
  },
  {
    id: 3,
    title: 'ML Engineer (Computer Vision)',
    company: 'MediScan Pro',
    founderId: 6,
    location: 'Hyderabad (On-site)',
    type: 'Full-time',
    salary: '₹30L – ₹55L',
    equity: '0.2% – 0.8%',
    stack: ['PyTorch', 'MONAI', 'DICOM', 'AWS SageMaker', 'Python'],
    description: 'Improve our radiology AI models on CT, MRI, and X-ray modalities. Join a team where your code directly impacts patient care timelines.',
    requirements: ['PhD or 4+ years in ML/CV', 'Medical imaging experience preferred', 'Strong publications or open-source contributions'],
    posted: '1 week ago',
    applicants: 12,
    logo: '🏥',
  },
  {
    id: 4,
    title: 'Growth Marketer',
    company: 'SkillBridge',
    founderId: 8,
    location: 'Remote',
    type: 'Full-time',
    salary: '₹10L – ₹18L',
    equity: '0.05% – 0.15%',
    stack: ['Meta Ads', 'Google Analytics', 'SQL', 'Content Strategy'],
    description: 'Own the top-of-funnel growth for 3 new vernacular markets launching in Q3. Drive learner acquisition and employer-side sales.',
    requirements: ['3+ years B2C growth experience', 'Vernacular market experience a huge plus', 'Data-driven decision making'],
    posted: '3 days ago',
    applicants: 44,
    logo: '📚',
  },
  {
    id: 5,
    title: 'Hardware Engineer (IoT)',
    company: 'AgriSense',
    founderId: 7,
    location: 'Pune',
    type: 'Full-time',
    salary: '₹15L – ₹25L',
    equity: '0.1% – 0.3%',
    stack: ['ESP32', 'MQTT', 'PCB Design', 'LoRaWAN', 'Embedded C'],
    description: 'Design and iterate on our next-gen sensor node that must survive Indian monsoons, function on 4G/LoRa, and cost under ₹2,500 at scale.',
    requirements: ['3+ years embedded hardware', 'BOM optimization experience', 'Field deployment experience in rural India preferred'],
    posted: '4 days ago',
    applicants: 8,
    logo: '🌾',
  },
];

export const demoMessages = [
  { id: 1, from: 'Rahul Mehta', fromId: 2, avatar: 'RM', text: 'Loved the NeuralNest pitch deck! Can we do a quick 30-min call this week?', time: '10:32 AM', unread: true },
  { id: 2, from: 'Deepa K.', fromId: 6, avatar: 'DK', text: 'Thanks for connecting! Your investor profile is very aligned with our Series A thesis.', time: 'Yesterday', unread: true },
  { id: 3, from: 'Priya Nair', fromId: 3, avatar: 'PN', text: 'Applied for the Full-Stack role — very excited about NeuralNest mission!', time: 'Mon', unread: false },
];

export const demoNotifications = [
  { id: 1, icon: '💬', text: 'Rahul Mehta sent you a message', time: '2 min ago', unread: true },
  { id: 2, icon: '👁️', text: 'Your startup profile was viewed 24 times this week', time: '1 hr ago', unread: true },
  { id: 3, icon: '🚀', text: 'AI Score updated for NeuralNest AI: 92/100', time: '3 hr ago', unread: false },
  { id: 4, icon: '📋', text: 'New application received for Senior Full-Stack Engineer', time: '5 hr ago', unread: false },
  { id: 5, icon: '🤝', text: 'Vikram Patel accepted your connection request', time: '1 day ago', unread: false },
];
